name: Release package
on:
  push:
    tags: ["v[0-9]+.[0-9]+.[0-9]+"]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Parse version info from tag
        run: |
          # GITHUB_REF is like refs/tags/v2.3.5, so strip the first 11 chars
          VERSION=${GITHUB_REF:11}
          echo "version=$VERSION" >> $GITHUB_ENV
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.9"
      - name: Insert version info
        run: |
          python3 remla01_lib/versioning.py --version ${{ env.version }}
      - name: Commit new version file to repo
        run: |
          echo "PACKAGE_JSON=$(jq -c . < remla01_lib/version.json)" >> $GITHUB_ENV
          echo '${{ fromJson(env.PACKAGE_JSON).version }}'
          
